### ISSUE TITLE
Sponsorship Copy

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#10]
I pulled the Sponsorship copy over from the 2014 website. Please take a look and let's update and make changes where appropriate. If we want to merge `learn` and `apply` then I'm game or maybe we don't need `apply` if you'd rather be contacted directly?

- http://ol579.gondor.co/sponsors/
- http://ol579.gondor.co/sponsors/learn/
- http://ol579.gondor.co/sponsors/apply/

**Comment by ipmb** [comment]
Going to go with 2 pages:

* http://ol579.gondor.co/sponsors/
* http://ol579.gondor.co/sponsors/apply/

@mightym is working on finishing up the styling.
