### ISSUE TITLE
Link to DjangoGirlsATX workshop in menu

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#108]
we need to make the workshop more discoverable on the website. Sent from the 🚙 or I'd add it.

**Comment by williln** [comment]
I can add this, but I'm not sure how to add an external link to the drop-down. Should DGATX go under "Schedule?" 

The link is djangogirls.org/djangoconus, btw.

**Comment by williln** [comment]
Looks like you or someone else did this, so I'm going to close the issue!

**Comment by jefftriplett** [comment]
Sorry, I did it from the car Sunday instead of Saturday before I forgot about it. I added a link under registration and schedule. Feel free to update it if it makes sense some place else or I can.
