### ISSUE TITLE
Add Diversity and Community sponsor tier 

### ISSUE THREAD

**Issue by ossanna16** [djangocon/djangocon.us#109]
Please add a Diversity and Community sponsor entry on https://2015.djangocon.us/sponsors/ so we can add the PSF, DSF and DEFNA to that section. Thank you!

**Comment by jefftriplett** [comment]
Should this be one tier or two separate tiers?

**Comment by jefftriplett** [comment]
Nevermind, I made them two separate plans. Fixed and deployed!
