### ISSUE TITLE
Disappearing background

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#11]
It looks like the background is disappearing in a few pages like the [sponsorship page](http://ol579.gondor.co/sponsors/).

Screenshot example: https://www.dropbox.com/s/a1vh9js4pox9m7n/Screenshot%202015-03-10%2021.39.08.png?dl=0

**Comment by mightym** [comment]
Should be fixed. If you see this occurring elsewhere please let me know

**Comment by jefftriplett** [comment]
Looks good! Thanks!
