### ISSUE TITLE
Change registration info page to reflect "sold out" 

### ISSUE THREAD

**Issue by williln** [djangocon/djangocon.us#110]
My proposed edit to this page is below.... 

## UPDATE: We are sold out! 

DjangoCon US is sold out at all levels (student, individual, and early bird). We recommend using the [Eventbrite registration page](https://djangoconus2015.eventbrite.com) to get on the waiting list for extra tickets, should they become available. **Tutorials are still available, though!**

We’ve worked hard to [lower ticket prices](http://2015.djangocon.us/blog/2015/05/15/announcing-our-conference-prices/) this year, and thus have low prices for students and individuals. 

[Get on the waiting list, or register for a tutorial at Djangocon 2015](https://djangoconus2015.eventbrite.com)

By registering for DjangoCon, you agree to abide by the [Code of Conduct](https://2015.djangocon.us/code_of_conduct/) at all events, whether officially sponsored by the conference or not.

[Reserve your hotel accommodation](https://resweb.passkey.com/go/DJANGO0915) to take advantage of our discounted room rates. This year the daily room rate for single or double occupancy is $139. Please use the reservation code of **DJANGO0915**.

Applications for Django Girls at DjangoCon (as a coach or as a participant) will be handled separately; please visit [Django Girls Austin](http://djangogirls.org/djangoconus/) for information about attending or coaching at the workshop. 

### What's Included?

Conference registration includes a light breakfast, lunch, and morning/afternoon break refreshments on the three conference days (Monday, Tuesday, & Wednesday). Conference attendees are also invited to our opening reception on Monday night.

Tutorial attendees will be provided with lunch and break refreshments. Tutorials are charged separately from registration and do not include admission to the main conference.

Sprint attendees will be provided lunch and break refreshments, courtesy of the DSF. There is no cost for these tickets, but for catering purposes if you plan to attend please add a ticket when registering.

Django Girls workshop coaches and attendees will be provided breakfast, lunch, and snacks, courtesy of Django Girls sponsors. 

### Financial Aid

Our tradition at DjangoCon is for [nearly everyone to pay](http://2015.djangocon.eu/news/everybody-pays/) — even the conference chair. There’s one exception: those who can’t afford to pay. If you want to attend DjangoCon, but can’t because of the cost, please  see the [Financial Aid page](https://2015.djangocon.us/financial_aid/) to learn more about Financial Aid for flights, hotel, and registration. **Financial aid applications are closed, and all aid has been allocated.** 
## Which ticket should I pick?

If you are a full-time student, at any level, please pick the student rate. If your employer is paying your way then please pick the corporate rate. If you work for a small company (five or fewer employees), or the corporate rate is not reasonable for your company, then please pick the individual rate. This is on the honor system: we trust you to pick the ticket most appropriate to your situation.

We also have a donation program and a diversity ticket program where sponsors and individuals may donate money or purchase an extra ticket to help support someone else who needs assistance. The more corporate tickets and diversity tickets we sell, and donations that we receive, the more student tickets and financial aid we can make available to attendees.

### Tutorial Rate

Tutorial registration is not included in regular conference registration prices. Each tutorial is in addition to regular registration. 

If you are only attending DjangoCon US tutorials and not the conference, there is no additional registration fee.

**Comment by craigbruce** [comment]
+1

**Comment by jefftriplett** [comment]
Copy looks great! I updated the website copy with the top section. I assume that's all that changed and we have other sections with html comments for various states that the text has been through. Let me know if you see anything else and we can update it too.
