### ISSUE TITLE
Logo / menu changes on non-home page.

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#14]
The DjangoCon logo only shows up on the homepage and it seems to disappear on any other pages.

![](https://www.evernote.com/shard/s27/sh/53d53201-0381-4356-83ba-7e661ef740c2/eaf2a312b75f468805c88bef58d92234/res/f515fd11-aeab-426c-8d93-f3728d4193c9/skitch.png)

**Comment by mightym** [comment]
It seems that the previous website versions made the logo optional.
Should i just include the brand always it in the site_base.html here:
https://github.com/djangocon/djangocon.us/blob/master/djangocon/templates/site_base.html#L56-L57
or keep it optional an add the on each template this block:
https://github.com/djangocon/djangocon.us/blob/master/djangocon/templates/homepage.html#L13-L15
?

**Comment by jefftriplett** [comment]
I guess my question then is does it simply or complicate the design to have the logo on every page? My preference would be to just keep the logo which I think looks better than seeing `home` on every page. If this is going to take hours or overly complicate things then I'll just re-add home link :)

**Comment by mightym** [comment]
Just added it to the base template :)
