### ISSUE TITLE
Text overflows into border

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon.us#16]
![djangocon in austin tx-1](https://cloud.githubusercontent.com/assets/319156/6628454/3b72ee70-c8cb-11e4-8463-21c18e685b46.png)

**Comment by mightym** [comment]
hmmm. tried to reproduce this. text breaks/wraps fine for me. i will try to find where this is happening

**Comment by ipmb** [comment]
I don't see the issue anymore.
