### ISSUE TITLE
Dashed line on slanted elements

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon.us#17]
![djangocon in austin tx-2](https://cloud.githubusercontent.com/assets/319156/6628469/69e045c8-c8cb-11e4-9f9b-973a9d2c03d7.png)

**Comment by jefftriplett** [comment]
I suspect this is related to issue #14.

**Comment by mightym** [comment]
I am aware of that issue. It's because of the css rotation. Haven't found a solution yet. At least we could get rid of the rotated elements. If this is blocking lets remove them. Otherwise let me figure out a solution :)
