### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon.us#19]
http://ol579.gondor.co/contact/

We either need to:

1. Test it works
2. Style it

Or remove it in lieu of an email link.

There's a link to it in the footer. @jefftriplett what do you prefer?

**Comment by jefftriplett** [comment]
I can verify that it works and goes to the webteam@ email address. Let me know if you or Mark want added to that list. 

I updated the `About` > `Contact Us` menu so that it links the page. Adding to the footer is fine too if there is room.

**Comment by ipmb** [comment]
Ok, just needs to be styled then. Passing to Mark.
