### ISSUE TITLE
Purchase web fonts

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#20]
We need to [purchase](https://www.myfonts.com/fonts/hvdfonts/brandon-printed/buy.html) *web* and *print* fonts for:

- Brandon Printed Two 
- Brandon Printed Extras

Do we need any more? 

Please reassign this ticket to me and let me know any additional fonts @mightym

**Comment by mightym** [comment]
I found a sans serif font in that family that fits well. Not sure if its worth 39$. I has been free to download in the last years. But haven't found updated information about this.
The font is called Brandon Text Medium
https://www.myfonts.com/fonts/hvdfonts/brandon-text/buy.html

It is deployed on dev. Integrated in the blog posts and the generic page contents.

**Comment by mightym** [comment]
Let me know if this font works for you

**Comment by jefftriplett** [comment]
Both **web** and **print** fonts for *Brandon Text Medium*?

**Comment by jefftriplett** [comment]
Purchased and sent to Mark!
