### ISSUE TITLE
Sprints Copy

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon.us#28]
http://ol579.gondor.co/sprints/

Remove for launch or change copy.

**Comment by ipmb** [comment]
Hidden for now.

**Comment by jefftriplett** [comment]
Needs proofed (copied from 2014 website): https://2015.djangocon.us/sprints/

**Comment by craigbruce** [comment]
Should DjangoCon AU be included in the first paragraph?

**Comment by craigbruce** [comment]
Otherwise, LGTM.

**Comment by jefftriplett** [comment]
Thanks! It was a carry over form last year's text.
