### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon.us#34]
We should drop a Google Analytics tag in there. Somebody might want that information at some point.

**Comment by jefftriplett** [comment]
I thought this was already deployed but it's in the develop branch still. I'm merging, deploying, and testing over lunch. I can add you to the GA account if your standard email address works.

**Comment by paltman** [comment]
Sure. All it needs is an env setting set with the code. Happy to set that up for you. paltman@gmail.com

**Comment by jefftriplett** [comment]
You are both added now. I set the env variable and I deployed some other changes before but I missed your changes. Those are deploying now. Thanks again!

**Comment by jefftriplett** [comment]
:+1: working
