### ISSUE TITLE
Link sponsor images to their website

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon.us#35]
Via a sponsor:

> Only thing I would change is to have the logo's click through to the sponsor websites also.  My first inclination was to click that and had to hunt around with my mouse to find the header was the link.

In reference to the sponsor list page

**Comment by jefftriplett** [comment]
I updated the logos on the sponsor list page to point to the sponsor's website link. Were you thinking there or just skipping the sponsor detail page and linking directly to their respective website?

**Comment by ipmb** [comment]
I think the homepage was fine (it linked to /sponsors/#sponsor-name), but
the logos on _that_ page didn't link anywhere. The ones on /sponsors/
should link to the sponsors' website.

**Comment by jefftriplett** [comment]
OK, great. That's fixed now.
