### ISSUE TITLE
SSL cert issues

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon.us#41]
https://twitter.com/alex_leonhardt/status/577740533931646976

Not sure what the root cause is, but Qualsys reports a few issues: https://www.ssllabs.com/ssltest/analyze.html?d=2015.djangocon.us&hideResults=on

**Comment by jefftriplett** [comment]
Hey @paltman, any ideas what we need to do here? I can ping Jannis too if it's the type of SSL cert we have causing the problem.

**Comment by paltman** [comment]
@jefftriplett I'm looking into it

**Comment by brosner** [comment]
I am looking into the Gondor SSL service now.

**Comment by brosner** [comment]
I have updated the Gondor SSL service. Please recheck and confirm the issue is resolved. If the issue is not resolved then there is something wrong with the certificate.

**Comment by jefftriplett** [comment]
Thanks @brosner and @paltman for the speedy resolution! I contacted Alex for verification.

**Comment by ipmb** [comment]
I'm still seeing the error here but haven't been able to replicate it elsewhere:

![crossbrowsertesting app](https://cloud.githubusercontent.com/assets/319156/6714519/51fb8606-cd5e-11e4-8c4f-ea1b6ba2e973.png)

I noticed the server is serving up an extra certificate. Could we pull that out and see if it solves the issue?

![ssl server test_ 2015 djangocon us powered by qualys ssl labs](https://cloud.githubusercontent.com/assets/319156/6714555/7e7b3104-cd5e-11e4-8652-d4b7c83c270e.png)

**Comment by jefftriplett** [comment]
Also weird I did a few deploys to push out Craig's change but pre-deploy the Qualys website showed us as an "A" but now is back to a "C". Did deploying rattle something loose?

**Comment by ipmb** [comment]
It looks like there's an issue with the chain: https://www.sslshopper.com/ssl-checker.html#hostname=2015.djangocon.us

![ssl checker - ssl certificate verify](https://cloud.githubusercontent.com/assets/319156/6714652/1cb47b5a-cd5f-11e4-9635-49026dbe4473.png)

**Comment by brosner** [comment]
I can update the certificate, but I need to full chain. Can someone send it over?

**Comment by brosner** [comment]
@jefftriplett the SSL service looks unchanged. I am seeing an A on the report. Perhaps local browser caching?

**Comment by jefftriplett** [comment]
@brosner I cleared my cache and it's an A now. Sorry to distract from the issue if it was unrelated.

I'm emailing Jannis about the cert and cc'ing everyone.

**Comment by jezdez** [comment]
@brosner https://www.gandi.net/static/CAs/GandiStandardSSLCA2.pem is the intermediate certificate that Gandi provides.

**Comment by jezdez** [comment]
But that seems not enough, as per http://wiki.gandi.net/en/ssl/intermediate you probably also need http://crt.usertrust.com/USERTrustRSAAddTrustCA.crt Sorry, but that was not in their SSL web GUI noted.

**Comment by brosner** [comment]
@jezdez that is what I need. Thank you. I will get it updated ASAP.

**Comment by brosner** [comment]
Certificate updated.

**Comment by ipmb** [comment]
LGTM :tada:
