### ISSUE TITLE
Evaluate/refactor rotation element stutters?

### ISSUE THREAD

**Issue by crccheck** [djangocon/djangocon.us#43]
On this particular machine, I'm using Firefox v36.0.1 and a large resolution (3840 x 2160) and the rotation effect isn't as smooth as I've seen it in other environments:
![rotate](https://cloud.githubusercontent.com/assets/189908/6742952/399c0aea-ce62-11e4-8909-c1167d8cbb62.gif)

Personally, I find the rotation effect to be distracting because my eye finds the anchor, then I move my mouse pointer to the anchor, but then the anchor moves.

**Comment by mightym** [comment]
Hmm, weird. I see on 36.0.1 the animation and its very smooth. Will dig into this

**Comment by crccheck** [comment]
I use Firefox and Chrome 50/50 on three separate machines, and it's only happening for me right now in one browser on one machine. I don't know how to use Firefox's css profiling (or if it has any) or I would have tried to get some of that data too.

**Comment by jefftriplett** [comment]
We remove the tilt on every page but the homepage. Marking it as resolved.
