### ISSUE TITLE
Escaped iframe in CMS page

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#46]
Just noticed: ![](https://www.evernote.com/shard/s27/sh/d8852c74-ef1e-4516-946d-fd225301f7e4/0064470162ad091acb3064930f8797af/deep/0/--DjangoCon-in-Austin,-TX.png)

**Comment by chefscott** [comment]
What's the correct way to embed the iframe? Or would you just rather it be a link that will take them offsite to Google Docs?

**Comment by jefftriplett** [comment]
Even easier, that'll work. Good idea!

Regards,
Jeff

https://calendly.com/jeff-triplett

**Comment by jefftriplett** [comment]
Updated the link to be clickable and I'm closing the ticket. Thanks again!
