### ISSUE TITLE
Diversity Copy

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#51]
https://2015.djangocon.us/diversity/

**Comment by williln** [comment]
I looked at DjangoCon US and came up with this:http://2015.djangocon.us/diversity/  

Lend me your edits and I'll add it to the drop-down this week!

**Comment by jefftriplett** [comment]
Looks great to me. cc'ing @mechanicalgirl and @kcunning for input.

**Comment by mechanicalgirl** [comment]
That is wonderful. I really like it. Succinct and clear. :)

**Comment by freakboy3742** [comment]
LGTM. 

One improvement I'd *like* to see would be for the diversity statement to come from the DSF, not the PSF; I know we're part of the Python community and all, but from a leadership perspective, it would be nice to have the DSF's position stated as well. 

Of course, this would require us to *have* a diversity statement, but other than the [preamble to the community Code of Conduct](https://www.djangoproject.com/conduct/), I'm not sure I can point at anything that is quotable.

We've got a DSF board meeting in the coming week; I'll see if, at the very least, I can get a board motion to publicly endorse the PSF's statement.

**Comment by jefftriplett** [comment]
Slightly off-topic: Might be worth re-looking at our CoC policy too. I was quite happy with what @jacobian came up after we added the additional [contact information](https://djangobirthday.com/conduct) for Django Birthday.

**Comment by williln** [comment]
I like that. I can also add local contact info for SafePlace, the Austin
rape crisis center, and similar contact info. I'll look at all that
tomorrow.

**Comment by williln** [comment]
I'm not happy with how this rendered, but the data is there (CoC contact). Still researching a counseling center: http://2015.djangocon.us/code_of_conduct/

**Comment by jefftriplett** [comment]
Let's go live with something on Friday that way Russ has time to talk to the DSF. @freakboy3742 if you need more time let us know but I'd rather have a diversity statement which we change later than not have one up.

**Comment by freakboy3742** [comment]
I've put this to the membership, and their reaction was positive to the idea of having a diversity statement, but they're not happy with just endorsing the PSF text - the consensus was that it was too wishy-washy and watered down. A couple of people are working on a new, less wishy-washy draft; but that's not likely to be done in the next 24 hours. So - I'd say launch; we can add/modify later if the DSF gets something together :-)

**Comment by audreyr** [comment]
About https://2015.djangocon.us/diversity/, really great work :)

* 1 minor suggestion: you might want to add a "such as" right before "women, people of color, LGBT people, and people with disabilities." This would clarify that the list of groups doesn't necessarily include all diverse groups.

About the DSF diversity statement which @freakboy3742 referred to, @pydanny and I have finished a draft in a Google doc and shared it with the DSF list for edits/corrections. If anyone involved with DjangoCon planning needs access in order to coordinate, let me or @pydanny know your Google Docs email.

**Comment by kennethlove** [comment]
Some content comments:

"iniquitous", while a great word, isn't really accessible to most people. If most people would have to look it up, many people will feel like you're talking down to them. I'd suggest replacing it with a lower reading-level word. Maybe something like:

> It is not just despicable that the minorities in our community -- women, people of color, LGBT people, and people with disabilities -- often find it hard to participate, their participation is vital to our community's health and is needed now more than ever.

**Comment by williln** [comment]
@kennethlove What about just plain "wrong?"

**Comment by kennethlove** [comment]
Wrong is good.

**Comment by williln** [comment]
@kennethlove and @audreyr: Your suggested changes have been made. 

I'm going to add the site to the drop-down menu tomorrow, but I can update it at any time to include the DSF diversity statement (which is awesome).

**Comment by williln** [comment]
I've added the diversity page to the drop-down and am going to close this issue. 

@audreyr, email me when the DSF statement is ready and I will update the page!
