### ISSUE TITLE
Financial Aid Copy

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#52]
http://2015.djangocon.us/financial_aid/

**Comment by williln** [comment]
Took a stab at it. What's the other org we're getting $5000 from? You mentioned it in our hangout but I didn't catch it. http://2015.djangocon.us/financial_aid/

**Comment by jefftriplett** [comment]
The other org is DEFNA. This might be easier to track the details on Trello since we can sublink tasks. I'll comment here: https://trello.com/c/dSp3nJCP/15-blog-financial-aid

**Comment by jefftriplett** [comment]
I'm going to close this since there is momentum in trello.
