### ISSUE TITLE
Contrast on proposal submission

### ISSUE THREAD

**Issue by williln** [djangocon/djangocon.us#55]
The contrast on the proposal submission page could use some work: https://www.dropbox.com/s/j6xkvv0tu64uoo1/contrast.jpg?dl=0  

The background color is #009ee3 and the text color is #96a623, which fails WebAIM's contrast checker (http://webaim.org/resources/contrastchecker/). Can this be changed to a friendlier level of contrast?

**Comment by mightym** [comment]
@jefftriplett do you think you can give me a dump of the current database. i guess i don't have these pages locally. (actually i even can't them on production :-) )

**Comment by jefftriplett** [comment]
Sorry @mightym, I bet the feature flags made it confusing. I fixed the data on staging and I updated the `proposal_base.json` fixture. I think the easiest way to see the page is to to use the refresh script (staging is updated): https://github.com/djangocon/djangocon.us/blob/master/refresh.sh

Let me know if that works for you. 

The page in question: https://2015.djangocon.us/proposals/submit/

**Comment by jefftriplett** [comment]
@williln Thank you for submitting the bug and for the copy suggestions you made via Twitter. We greatly appreciate your help!

**Comment by williln** [comment]
@jefftriplett No problem! Thanks for responding :)
