### ISSUE TITLE
Duckling: Nix / Update?

### ISSUE THREAD

**Issue by kcunning** [djangocon/djangocon.us#6]
If we choose to use Duckling again, we will eventually need to create a new group and update the internal links.

https://duckling.us/events/djangocon2014/

**Comment by jefftriplett** [comment]
Let's remove the ducky links for now and we can re-add later if there is interest.

**Comment by jefftriplett** [comment]
I'm adding @mightym to the thread to remove the ducky from the last few templates. Might just be on the schedule page:

- http://ol579.gondor.co/schedule/

**Comment by mightym** [comment]
Is removed from the schedule page. If it somewhere else pops up let me know.

**Comment by jefftriplett** [comment]
Good good, thanks!
