### ISSUE TITLE
Background missing when reviewing proposals

### ISSUE THREAD

**Issue by craigbruce** [djangocon/djangocon.us#62]
Marking it hard to read, normally it is green?

![screen shot 2015-04-13 at 6 39 33 pm](https://cloud.githubusercontent.com/assets/1503648/7127020/98b08dd6-e20c-11e4-94b4-a7bc0916aae0.png)

**Comment by jefftriplett** [comment]
I think it's worth pointing out that this doesn't blow up until the browser is full screened. I just noticed it because I have a weird tiling setup and I constantly resize / move my windows.

**Comment by jefftriplett** [comment]
I wonder if this is related to: #63
