### ISSUE TITLE
Sprints Copy

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#64]
From a group email with @freakboy3742:

> A "sprint" is really the entire group activity - everyone turns up "to sprint" - it isn't really a set of separate groups. There are definitely groups inside that whole who are sprinting on specific activities, but it's not a thing where you need to find a group ahead of time. You turn up, find a seat, and then find something to work on. In the past, we've often had a "pitch session" - either on the last day of the conference, or early on the first day, where people who have projects in mind get a minute or two to say what they want to work on. 

> If you don't turn up with something specifically in mind, there's always Django's ticket tracker with a couple thousand ideas of things to fix.

> If you're an old hand, a sprint is an opportunity to have some high-bandwidth discussion with other interested people about that feature or bug that's been on your mind

> If you're an old hand at *using* Django, but you've never contributed, it's your chance to make the leap into being a contributor - fix your first bug. If Daniele is there, he can usually be counted on to run a "Don't be afraid to commit" workshop.

> If you've got a project that is Django-related, but not part of core), it's a chance to find new contributors for your project. 

Also, need to DjangoGirls meet up info.

**Comment by jefftriplett** [comment]
In progress but assigning to Craig since the bulk of the work is in the sprint form that he's created.

**Comment by williln** [comment]
Django Girls: 

> [Django Girls Austin](http://djangogirls.org/djangoconus/) will be taking place on the first day of the sprints, and we invite you to participate! Visit their website to sign up to coach (men can coach, too!), or contact the organizers Lacey Williams Henschel and Barbara Shaurette at [djangoconus@djangogirls.org](mailto:djangoconus@djangogirls.org) if your company would like to sponsor this workshop. In the meantime, follow Django Girls ATX on [Twitter](http://twitter.com/djangogirlsatx) and [Facebook](https://www.facebook.com/djangogirlsatx) for the latest updates on the workshop. 

CC @mechanicalgirl for input on the DG copy.
