### ISSUE TITLE
Sponsors get smooshed on smaller screens

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon.us#65]
![welcome djangocon in austin tx](https://cloud.githubusercontent.com/assets/319156/7321968/5f03adda-ea62-11e4-82fc-30cfb5a282db.png)

**Comment by fcurella** [comment]
works for me on chrome 42 and safari 8

chrome:

![screen shot 2015-04-30 at 3 48 41 pm](https://cloud.githubusercontent.com/assets/89607/7422208/9f8a7c56-ef50-11e4-9a58-b5287ea64f10.png)

safari:

![screen shot 2015-04-30 at 3 49 51 pm](https://cloud.githubusercontent.com/assets/89607/7422213/aba370ba-ef50-11e4-9009-b71dc49ed5f5.png)
