### ISSUE TITLE
Repeat Email

### ISSUE THREAD

**Issue by issackelly** [djangocon/djangocon.us#70]
"repeat email" is bold and forces caps on the login page. Latest Chrome.

**Comment by jefftriplett** [comment]
Thank you for the report! 

This is fixed by @fcurella in #74.

![](https://www.evernote.com/shard/s27/sh/e5838a24-4f92-4d4a-abbd-05dae3a5be89/d78864e24f4e0a6b699cf55fe59475c3/deep/0/--DjangoCon-in-Austin,-TX.png)

**I'll be deployed today.**
