### ISSUE TITLE
Typography update for content and review pages

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#73]
The bullet points are kind of overwhelming in the non-post homepage views. Ideally if we could change:

- left justify instead of centering text
- normal case instead of upper case

**Please note:** We want to keep this style on the homepage though.

![](https://www.evernote.com/shard/s27/sh/f0302f23-566a-4a20-bf96-117136baf937/69d0229afdfac67be3adb2df8cbe287c/deep/0/Financial-Aid---DjangoCon-in-Austin,-TX.png)

Example page: 
http://2015.djangocon.us/financial_aid/

Proposals are hard to read too from the all upper case too. I think this is just a page style that needs applied like the CMS pages have:

![](https://www.evernote.com/shard/s27/sh/cecfcc16-74d6-4f75-ac21-c2f918040f86/6427478d388aecc8325951ab1f17a933/deep/0/45-minute-test-talk---DjangoCon-in-Austin,-TX.png)

**Comment by jefftriplett** [comment]
The style looks great on the homepage but on the text copy pages it's a little much.

**Comment by fcurella** [comment]
turns out everything in that's in the BrandonPrinted-Two font is uppercase because the font itself has only uppercase glyphs. We need to get in touch with whoever generated the font to change the export settings on the font service

**Comment by fcurella** [comment]
![screen shot 2015-05-06 at 4 41 44 pm](https://cloud.githubusercontent.com/assets/89607/7504306/d287a40e-f40e-11e4-932d-767a04c661ad.png)

bullet pointing fingers? yay or still nay?

**Comment by jefftriplett** [comment]
I'd rather lose the finger and gain non-CAPS then not. That font is an uppercase only font. I'd prefer the style not impact the homepage though.

**Comment by fcurella** [comment]
my goal is keep the home intact. fingers and caps/non-caps are two independent issue. They even use two different font files

**Comment by fcurella** [comment]
to clarify, with the settings that we have now, in order to do non-caps I'll have to change the font for list-items to the sans-serif one.

The fingers can either stay or not, whichever you prefer.

**Comment by williln** [comment]
The fingers don't bother me. I'm just happy it's left justified now! Thank you!

**Comment by fcurella** [comment]
![screen shot 2015-05-06 at 5 11 22 pm](https://cloud.githubusercontent.com/assets/89607/7504851/f9c97228-f412-11e4-8b20-8474a7229693.png)

**Comment by jefftriplett** [comment]
LGTM. I'm going to push it to staging though so we can make sure the homepage doens't change.

**Comment by jefftriplett** [comment]
@fcurella I deployed to staging which you can see here: http://ol579.gondor.co/ -- If you are fine with it, I'll merge and push it out to production.

**Comment by jefftriplett** [comment]
@fcurella did you have any luck with the review pages? I had someone ping me about this today. If I just need to apply a style let me know. Thanks!

**Comment by jacobian** [comment]
the review pages are fairly not great, @fcurella asked for a screenshot so here goes:

![](https://dl.dropboxusercontent.com/s/g7g3yxyymicmdmy/2015-05-18%20at%201.14%20PM.png

**Comment by jefftriplett** [comment]
![](https://www.evernote.com/shard/s27/sh/35c6cdfc-b302-4e24-8647-c64483c09502/f55d0a1b950da88f40b259bda1e8397d/deep/0/--DjangoCon-in-Austin,-TX.png)

**Comment by jefftriplett** [comment]
I think we are good now. Thanks everyone!
