### ISSUE TITLE
Some forms are unsubmittable using the submit button

### ISSUE THREAD

**Issue by crccheck** [djangocon/djangocon.us#79]
When there's a `<hr>` below form buttons, the box for the `<hr>` overlays over the buttons and prevents clicks from reaching them.

Workaround: submit using the keyboard `Enter` key

Browser: FireFox and Chrome
Known urls: https://2015.djangocon.us/account/signup/ and https://2015.djangocon.us/account/login/
Screenshot:
![screen shot 2015-05-08 at 2 34 31 pm](https://cloud.githubusercontent.com/assets/189908/7544132/173b4740-f590-11e4-9ece-9a668a806d45.png)

**Comment by jefftriplett** [comment]
Thank you for reporting that issue @crccheck and thank you for the quick fix @fcurella!
