### ISSUE TITLE
Password Reset is off

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon.us#81]
Looks like there is something off on the Password Reset screen: https://2015.djangocon.us/account/password/reset/

![](https://www.evernote.com/shard/s27/sh/71983e1d-91af-40f7-8a3f-85cf13ec2c8c/024cb9e2e54a66497abfa6b4ade14da0/deep/0/--DjangoCon-in-Austin,-TX.png)

**Comment by fcurella** [comment]
@jefftriplett Note that the 'contact us at.' is incomplete because `THEME_CONTACT_EMAIL` is not set in the settings.
