### ISSUE TITLE
Sponsor header graphics are misaligned

### ISSUE THREAD

**Issue by craigbruce** [djangocon/djangocon.us#85]
Much like in #77. See https://2015.djangocon.us/sponsors/

![screen shot 2015-05-11 at 11 28 20 pm](https://cloud.githubusercontent.com/assets/1503648/7580602/700b8838-f835-11e4-930c-397b1fe510c4.png)

**Comment by jefftriplett** [comment]
@fcurella care to take a look?

**Comment by fcurella** [comment]
on it

**Comment by craigbruce** [comment]
Excellent - thanks!

**Comment by ipmb** [comment]
Seeing a few more issues around this...

Same issue on the homepage
![welcome djangocon in austin tx](https://cloud.githubusercontent.com/assets/319156/7602065/24e82662-f8e5-11e4-9fbc-ec37dc5c9824.png)

It looks like the font is broken on the sponsors page for the headings. It should be in all caps like the screenshot above. Instead, I see this:

![about our sponsors djangocon in austin tx](https://cloud.githubusercontent.com/assets/319156/7602088/509367d6-f8e5-11e4-84cb-cecf19e8b154.png)

Finally, the text should go above, not below the ribbon thingies. Here's what it looked like for the initial launch:

![djangocon portfolio by ipmb pull request 215 lincolnloop_lincolnloop](https://cloud.githubusercontent.com/assets/319156/7602115/ade14c50-f8e5-11e4-9640-86ac6bde8406.png)

**Comment by jefftriplett** [comment]
It's looking closer but the style is different than the original version:

![](https://www.evernote.com/shard/s27/sh/ba25fef1-3cbe-4c39-9d6b-db49af8272aa/5f4cc6bcbba6c1708902a474d5f0e645/deep/0/Welcome---DjangoCon-in-Austin,-TX.png)

**Comment by jefftriplett** [comment]
My bad. This is great!

**Comment by jefftriplett** [comment]
How about these? 

![](https://www.evernote.com/shard/s27/sh/0a3d7595-17e1-4ae9-bace-49a776a39b21/1622f2a212ff2441cf76fc12aad600f8/deep/0/Mark-your-calendars!---DjangoCon-in-Austin,-TX.png)
