### ISSUE TITLE
Sponsorship Level

### ISSUE THREAD

**Issue by jambonrose** [djangocon/djangocon.us#94]
On:

- https://2015.djangocon.us/
- https://2015.djangocon.us/sponsors/

The top tier is listed as Diamond. I believe (following conversation with Peter) that this should be Platinum.

@ipmb Could you please confirm this?

**Comment by jefftriplett** [comment]
Confirmed, Diamond is the top: https://2015.djangocon.us/become-sponsor/ and Platinum is the next best. I'm completely missing the context here?

**Comment by jambonrose** [comment]
Ah! I think I misunderstood the problem.

The trello board lists Caktus as being Platinum, but it's currently listed as Diamond on the website. The issue is not about the naming of the section (as I first thought) but with the section Caktus appears in.

**Comment by jefftriplett** [comment]
Gotcha. Thanks for pointing it out and it should be fixed now.
